'''
TESTING
Make working 6x8 grid
'''
import tkinter as tk

window = tk.Tk()


A1 = tk.Button(window, text='SPACE')
A2 = tk.Button(window, text='SPACE')
A3 = tk.Button(window, text='SPACE')
A4 = tk.Button(window, text='SPACE')
A5 = tk.Button(window, text='SPACE')
A6 = tk.Button(window, text='SPACE')
A7 = tk.Button(window, text='SPACE')
A8 = tk.Button(window, text='SPACE')
B1 = tk.Button(window, text='SPACE')
B2 = tk.Button(window, text='SPACE')
B3 = tk.Button(window, text='SPACE')
B4 = tk.Button(window, text='SPACE')
B5 = tk.Button(window, text='SPACE')
B6 = tk.Button(window, text='SPACE')
B7 = tk.Button(window, text='SPACE')
B8 = tk.Button(window, text='SPACE')
C1 = tk.Button(window, text='SPACE')
C2 = tk.Button(window, text='SPACE')
C3 = tk.Button(window, text='SPACE')
C4 = tk.Button(window, text='SPACE')
C5 = tk.Button(window, text='SPACE')
C6 = tk.Button(window, text='SPACE')
C7 = tk.Button(window, text='SPACE')
C8 = tk.Button(window, text='SPACE')
D1 = tk.Button(window, text='SPACE')
D2 = tk.Button(window, text='SPACE')
D3 = tk.Button(window, text='SPACE')
D4 = tk.Button(window, text='SPACE')
D5 = tk.Button(window, text='SPACE')
D6 = tk.Button(window, text='SPACE')
D7 = tk.Button(window, text='SPACE')
D8 = tk.Button(window, text='SPACE')
E1 = tk.Button(window, text='SPACE')
E2 = tk.Button(window, text='SPACE')
E3 = tk.Button(window, text='SPACE')
E4 = tk.Button(window, text='SPACE')
E5 = tk.Button(window, text='SPACE')
E6 = tk.Button(window, text='SPACE')
E7 = tk.Button(window, text='SPACE')
E8 = tk.Button(window, text='SPACE')
F1 = tk.Button(window, text='SPACE')
F2 = tk.Button(window, text='SPACE')
F3 = tk.Button(window, text='SPACE')
F4 = tk.Button(window, text='SPACE')
F5 = tk.Button(window, text='SPACE')
F6 = tk.Button(window, text='SPACE')
F7 = tk.Button(window, text='SPACE')
F8 = tk.Button(window, text='SPACE')

A1.grid(row=1, column=1)
A2.grid(row=2, column=1)
A3.grid(row=3, column=1)
A4.grid(row=4, column=1)
A5.grid(row=5 , column=1)
A6.grid(row=6 , column=1)
A7.grid(row=7 , column=1)
A8.grid(row=8 , column=1)
B1.grid(row=1 , column=2)
B2.grid(row=2 , column=2)
B3.grid(row=3 , column=2)
B4.grid(row=4 , column=2)
B5.grid(row=5 , column=2)
B6.grid(row=6 , column=2)
B7.grid(row=7 , column=2)
B8.grid(row=8 , column=2)
C1.grid(row=1 , column=3)
C2.grid(row=2 , column=3)
C3.grid(row=3 , column=3)
C4.grid(row=4 , column=3)
C5.grid(row=5 , column=3)
C6.grid(row=6 , column=3)
C7.grid(row=7 , column=3)
C8.grid(row=8 , column=3)
D1.grid(row=1 , column=4)
D2.grid(row=2 , column=4)
D3.grid(row=3 , column=4)
D4.grid(row=4 , column=4)
D5.grid(row=5 , column=4)
D6.grid(row=6 , column=4)
D7.grid(row=7 , column=4)
D8.grid(row=8 , column=4)
E1.grid(row=1 , column=5)
E2.grid(row=2 , column=5)
E3.grid(row=3 , column=5)
E4.grid(row=4 , column=5)
E5.grid(row=5 , column=5)
E6.grid(row=6 , column=5)
E7.grid(row=7 , column=5)
E8.grid(row=8 , column=5)
F1.grid(row=1 , column=6)
F2.grid(row=2 , column=6)
F3.grid(row=3 , column=6)
F4.grid(row=4 , column=6)
F5.grid(row=5 , column=6)
F6.grid(row=6 , column=6)
F7.grid(row=7 , column=6)
F8.grid(row=8 , column=6)


window.mainloop()
